plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/beto/Library/CloudStorage/OneDrive-Personal(2)/Freelancer/clientes/web/Andrea Katich Kurk - Fisioterapeuta"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]